export const packs = [
  {
    id: 1,
    title: "Starter",
    type: "Pack",
    price: 195.0,
    maxQuantity: 1,
    image: "/e-nite/Pack-1-Starter.jpg",
    description:
      "This Pack has everything you need to transform any space or room into a mini club. All you need is your iPhone/iPod/laptop (or any other music source) and the party may begin!",
    equipmentList: [
      "Two Behringer Speakers (2 x 250W RMS)",
      "One Behringer Amplifier",
      "Behringer Mixboard/Mixer",
      "Dispatcher Light Switch",
      "1 Lightstand JB",
      "Smoke Machine 1000W Antari + liquid + remote",
      "ADJ Revo 4 LED + remote",
      "ADJ Galaxian LED & Laser + remote",
      "Martin Moonlight",
      "Stroboscope",
      "UV Blacklight LED",
      "Power & audio cables",
      "Extension cords",
    ],
    optionalEquipment: [
      {
        item: "Speaker Stands",
        price: 5,
      },
      {
        item: "Bluetooth Receiver",
        price: 5,
      },
      {
        item: "Active Subwoofer Behringer 500W",
        price: 45,
      },
    ],
  },
  {
    id: 2,
    title: "Sound",
    type: "Pack",
    price: 95.0,
    maxQuantity: 1,
    image: "/e-nite/Pack-2-Sound.jpg",
    description:
      "All you need to play loud music like a DJ with this simple but effective kit.",
    equipmentList: [
      "Two Behringer Speakers (2 x 250W RMS)",
      "One Amplifier Behringer",
      "Behringer Mixboard/Mixer",
      "1 wired Behringer Microphone",
      "XLR 6m cable",
      "Audio & Power cables",
    ],
    optionalEquipment: [
      {
        item: "Speaker Stands",
        price: 5,
      },
      {
        item: "Bluetooth Receiver",
        price: 5,
      },
      {
        item: "Active Subwoofer Behringer 500W",
        price: 45,
      },
    ],
  },
  {
    id: 3,
    title: "Lightshow",
    type: "Pack",
    price: 160.0,
    maxQuantity: 1,
    image: "/e-nite/Pack-3-Lightshow.jpg",
    description:
      "This pack will provide you and yours guests a beautiful and impressive light-show.",
    equipmentList: [
      "Double Full Light-stand JB",
      "Smoke Machine 1000W Antari + Remote",
      "Dispatcher Light Controller Switch",
      "Black light UV Tube LED",
      "Stroboscope",
      "2 x Moonlight Eurolite",
      "American DJ Revo 4 LED + Remote",
      "American DJ Galaxian LED & Laser + remote",
      "Laser Double RGY",
      "Traffic Lights",
      "Extension cords",
    ],
  },
  {
    id: 4,
    title: "Fiesta",
    type: "Pack",
    price: 295.0,
    maxQuantity: 1,
    image: "/e-nite/Pack-4-Fiesta.jpg",
    description:
      "A complete and professional Sound & Light kit with an added double Beer Tap. What more do you want?",
    equipmentList: [
      "Portable double beer tap",
      "Gas Aligal for the beer tap",
      "Two Behringer Speakers",
      "One Amplifier Behringer",
      "Wired Behringer Microphone",
      "Mixboard BST",
      "Dispatcher Light Switch",
      "Moonlight JB Twin Ball",
      "Lightstand JB",
      "Smoke Machine 1000W Antari + remote",
      "Stroboscope",
      "Moonlight Eurolite",
      "American DJ Revo 4",
      "Laser double RGY",
      "UV Blacklight LED",
      "Power Cords",
      "Extension cables and all necessary accessories",
    ],
  },
  {
    id: 5,
    title: "Microphones",
    type: "Pack",
    price: 30.0,
    maxQuantity: 1,
    image: "/e-nite/Pack-5-Microphones.jpg",
    description:
      "A comprehensive set of microphones suitable for karaoke nights, live performances, or even public speaking engagements!",
    equipmentList: [
      "3 Behringer Microphones",
      "3 Microphone Stands",
      "3 Microphone Clips",
      "3 XLR Cables",
      "1 Microphone Travelling Case",
    ],
  },
  {
    id: 6,
    title: "Spots",
    type: "Pack",
    price: 100.0,
    maxQuantity: 1,
    image: "/e-nite/Pack-6-Spots.jpg",
    description: "Perfect for stages, music bands and general atmosphere!",
    equipmentList: [
      "2 Eurolite PAR LED spots (big)",
      "2 Eurolite PAR LED spots (small)",
      "2 Briteq PAR LED spots",
      "2 light stands",
      "1 dispatcher light controller",
      "5 XLR cables",
      "Power cables",
    ],
  },
];