import './globals.css'
import type { Metadata } from 'next'
import { Locale, i18n } from '@/i18n.config'
import Header from './components/layout/NavHeader'
import { Inter } from 'next/font/google'
import CartProvider from '@/lib/redux/CartProvider'
import ShoppingCart from './components/products/ShoppingCart'
import Footer from './components/layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'e-nite',
  description: 'Generated by create next app'
}

// Used in combination with dynamic route segments to statically generate routes at build time
// Not sure exactly how that words - above copied from docs
export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale } // Typed for lang params
}) {
  return (
    // html lang is configured with params.lang
    <html lang={params.lang}>
      <body className={inter.className}>
        <CartProvider>
        <ShoppingCart />
          {/* {params.lang === 'en' && <ShoppingCart />}
          {params.lang === 'fr' && <ShoppingCartFR />} */}
          <Header lang={params.lang} />
          <main>{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  )
}
